### ISSUE TITLE
MP REST Client: ID Critique

### ISSUE THREAD

**Issue by sishida** [OpenLiberty/draft-guide-microprofile-rest-client#3]
General notes:
- [x] I'd avoid referring to "developers" or the "user" if at all possible. Refer to the developer/user as "you," or write in the imperative as a command, such as, "**You can use** this thing to do that task." or "**Use** this thing to do that task."
- [x] If something's in a code phrase, follow it up with a word that tells what it is. These "label words" are important if we ever want to translate the guides. Some code phrases already have these words, which is great, but I also saw some without them. For example, one sentence mentions "the 'inventory' service"--that's what we want. :) That's better than just the word 'inventory' by itself. File paths, file names, URLs, etc. can all take "label words" like this.

Writing the RESTful client interface
- [x] What makes the MicroProfile Rest Client API get added as a dependency to the pom.xml file?
--And how does this API relate to the mpRestClient-1.0 feature being enabled in the src/main/liberty/config/server.xml file? If we just want to state the fact that this feature is also enabled, maybe make the mpRestClient-1.0 feature sentence its own paragraph.
--And then the subject of the system service comes up...Maybe provide the info in these paragraphs as a list or table that states what's added, where it's added, and what it does? As it is, this section might make readers feel like they're being pulled in multiple directions in a short amount of time.

Testing the application
- [x] I'd say "you might have introduced a bug" instead of "you must have."

Great work! You're done!
- [x] I'd say, "They demonstrate additional technologies" and "expand on what you built in this guide."
- [x] We try to avoid directional words because they aren't very useful to users who are visually impaired and use screen readers.

**Comment by yeekangc** [comment]
Tagging a couple comments if that's alright:

- "Rest" in "Rest Client" should be "REST".
- Title:  We should work on it further.  I would suggest something like "Invoking RESTful microservices" or "Accessing microservices" to be consistent with the other guides.  The "using" part can come in the abstract.

**Comment by JunyiSun** [comment]
https://github.ibm.com/was-liberty/openliberty-guides-team/issues/212

**Comment by JunyiSun** [comment]
Fixed by #17

**Comment by JunyiSun** [comment]
ID Review done by #33 #34
