### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-rest-client#35]
- [x] We should tie the introduction and the below to the "template interface" used in the title.  I'll focus on the simplicity of creating an interface and then, you can use the client right away via injection or the builder.  The benefits of one over the other and when to use what can be elaborated in the below.

`You will learn how to create and register the client interface and handle exceptions through ResponseExceptionMappers mapper class. Then, you will instantiate the client and use it in the inventory service. It is possible to do so by using two different approaches: CDI with the help of MicroProfile Config method, and the RestClientBuilder method. You can choose either way to instantiate the client in the future, but in this guide you will explore both methods in order to handle different scenarios to provide a valid base URL. You must have a valid base URL to instantiate the RESTful client.`

The introductory section can be made clearer and tighter in general.

- [x] Multiple spots with the below: **Already fixed in the latest version**

`Get your fully qualified domain name (FQDN) first, then visit the http://localhost:9080/inventory/systems/&lt;your_hostname&gt; URL by replacing <your_hostname> with your FQDN. You will see the same system property information, but the process of getting this information is actually implemented differently.`

Need to escape angle brackets properly or try a different sample URL.

- [x] Is it the "service" that actually does these? **The service uses the MicroProfile Rest Client feature to do these, the sentence here is adapted from Andy McCright's explanation to me**

`The service automatically builds and generates an implementation for the SystemClient interface, because the JAX-RS annotations in the interface tell the RESTful service what to do.`

- [x] What is significant about the scope?

`The @Dependent annotation tells the service that the scope of the interface is dependent on the class that they get injected into.`

- [x] I think we can better explain why we need to do the below?

`In the SystemClient interface, the getProperties() method might throw an UnknownUrlException exception if the response from the system service is 404 NOT FOUND, and @RegisterProvider(UnknownUrlExceptionMapper.class) registers the response exception mapper. Implement the actual exception class and the mapper class to see how this mechanism works.`

And, speak in terms of the remote service?  Basically, you define an interface to map to what you want to invoke on the remote service.  Then, you have these mappers to handle exceptions?

- [x] If we have better explained why CDI in the sections before, it will be easier to understand the below i.e. why it is easy.  We should still tie it back to what is in the earlier sections.

`Now, instantiate the SystemClient interface and use it in the inventory service. If you only want to connect with the default host name, it is easy to instantiate the SystemClient by using CDI annotations.`

- [x] Better formatting for this block of code so it shows better on the website?

```
      SystemClient customRestClient = RestClientBuilder.newBuilder()
                                                       .baseUrl(customURL)
                                                       .register(
                                                           UnknownUrlExceptionMapper.class)
                                                       .build(SystemClient.class);
```

- [x] I don't follow the below:

` Since InventoryManager class is another CDI managed object and CDI requires one to inject the SystemClient, you add the client here.`

- [x] I struggled with the service "providing the hostname":

`The inventory service might also provide a different host name rather than the default localhost. Set the host name as a variable and build the client by using the RestClientBuilder method.`

For services that are known and "static", you create interfaces and inject the clients; You use the client builder if the remote service isn't "static" and can't be configured, you use the builder?

Again, speak in terms of what developers need to understand besides what is in the implementation.

- [x] The below is unclear:

`To see whether the tests detect a failure, change the base URL in the configuration file, so that when the inventory service tries to access the invalid URL, a 404 NOT FOUND exception is thrown. Re-run the Maven build. You will see a test failure occur. Re-start the liberty server and visit http://localhost:9080/inventory/systems/localhost, you will see the error message ERROR: Unknown hostname or the system service may not be running on localhost.`

And, "liberty" should be "Liberty"?  Not sure if it serves a meaningful purpose either.

So, you should be changing the base URL to an invalid URL so you get a 404 to check/test that the tests are really tests.  After that, why do we need to restart and hit that URL?

- [x] I wouldn't just say MicroProfile application but tie it back to the focus of the guide and what we have here?

`You just built and tested a MicroProfile application with MicroProfile Rest Client and Open Liberty.`

**Comment by JunyiSun** [comment]
Fixed by #37

**Comment by yeekangc** [comment]
@evelinec @sishida, please help ensure that the above items are appropriately addressed in the latest PR.  Thanks.

**Comment by sishida** [comment]
ID review completed!

**Comment by yeekangc** [comment]
Issues addressed so closing.
