### ISSUE TITLE
MP REST Client: Outline review

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-rest-client#4]
Can add more info for the two approaches, RestClientBuilder and CDI, or perhaps link to existing info, if they’re good?

- [x] After starting the application, you can access the following two microservices:
	•	http://localhost:9080/system/properties retrieves the information for a specific host 
	•	http://localhost:9080/inventory/systems retrieves the information for a list of all previously registered hosts 
=> the inventory/systems url is shown, and not the inventory/system/<hostname> url, there’s no way for user at this point to add “previously registered hosts”..
=> looks like listing the inventory/system/<hostname> url is enough for this guide. this is the url that calls the system service through the REST client
=> not sure we need to list the system/properties url

- [x] we’d state why we need to add the feature in the server.xml. Just stating it is being added is not enough, good to know why it needs to be added, and/or what it does.
The mpRestClient-1.0 feature is also enabled in the src/main/liberty/config/server.xml file.

**Comment by JunyiSun** [comment]
After discussion, we decided not to add additional links to CDI and RestClientBuilder
