### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-microprofile-rest-client#41]
**Getting Started**

- [x] It could be useful to add that users can find what their hostname is by typing hostname into their command line.

**Writing the RESTful client interface**

- [x] In the fourth paragraph, I feel like the sentence should not start with "Next, create ..." since there were no previous instructions for this section.  

**Injecting the client**
- [x] I think the following sentence would be more clear if you replaced because with through.
>  Since the InventoryManager class is @ApplicationScoped, and the SystemClient CDI bean maintains the same scope because of the @Dependent annotation, the client is initialized once per application.

> Since the InventoryManager class is @ApplicationScoped, and the SystemClient CDI bean maintains the same scope **through** the @Dependent annotation, the client is initialized once per application.

**Testing the application**

- [x] Instead of repeating the step that users should stop the server from running (mvn stop), perhaps we could emphasize it more the first time you mentioned to stop the server in **Getting Started** and **Building and Running the application**
**JS: I cannot remove the part where it says "repeating the step that users should stop the server from running" because it's in the guides-common (common files that is shared by all guides). I did emphasize it more the first time mentioned to stop the server in **Getting Started****

**Comment by JunyiSun** [comment]
fixed by #42 , approved by Justine
